#
# This is a server HOT template defining a single compute server.
#
heat_template_version: 2013-05-23

description: >
  Server HOT template that just defines a single server.
  Connects to the port 8000 with HTTP protocol of the instance
  A requests from it gives you the A hello from the machine and its name.

parameters:
  key_name:
    type: string
    description: Name of an existing key pair to use for the server
    default: cloudKey
  flavor:
    type: string
    description: Flavor for the server to be created
    default: INF4410-mini
  image:
    type: string
    description: Image ID or image name to use for the server
    default: INF4410-Ubuntu-trusty-mini
  db_port:
    type: number
    description: Database port number
    default: 50000
    constraints:
      - range: { min: 40000, max: 60000 }
        description: Port number must be between 40000 and 60000

resources:
  server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      user_data_format: RAW
      networks: [{ "network": inf4410-net}]
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            echo "Starting up server"
            echo "Port: "
            echo db_port
            wget https://raw.githubusercontent.com/houssemmh/INF4410-TP3/master/server.py
            python server.py
          params:
            db_port: { get_param: db_port }

outputs:
  server_networks:
    description: The networks of the deployed server
    value: { get_attr: [server, networks] }
